web/router.ex
defmodule CarlabsComments.Router do
  use CarlabsComments.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CarlabsComments.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", CarlabsComments do
    pipe_through :api

    resources "/comments", CommentController
  end

  scope "/auth", CarlabsComments do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/", CarlabsComments do
    pipe_through :browser # Use the default browser stack

    get "/*path", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", CarlabsComments do
  #   pipe_through :api
  # end
end

lib/carlabs_comments/endpoint.ex
defmodule CarlabsComments.Endpoint do
  use Phoenix.Endpoint, otp_app: :carlabs_comments

  socket "/socket", CarlabsComments.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :carlabs_comments, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_carlabs_comments_key",
    signing_salt: "SLZ2fdlT"

  plug CarlabsComments.Router
end

lib/carlabs_comments/repo.ex
defmodule CarlabsComments.Repo do
  use Ecto.Repo, otp_app: :carlabs_comments
end

web/models/comment.ex
defmodule CarlabsComments.Comment do
  use CarlabsComments.Web, :model

  @derive {Poison.Encoder, only: [:comment, :id, :user, :polarity]}
  schema "comments" do
    field :comment, :string
    field :polarity, :string
    belongs_to :user, CarlabsComments.User

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:comment])
    |> cast(params, [:polarity])
    |> validate_required([:comment])
  end
end

web/models/user.ex
defmodule CarlabsComments.User do
  use CarlabsComments.Web, :model

  @derive {Poison.Encoder, only: [:nickname, :avatar_url]}
  schema "users" do
    field :email, :string
    field :nickname, :string
    field :avatar_url, :string
    field :provider, :string
    field :token, :string
    has_many :comments, CarlabsComments.Comment

    timestamps()
  end

  def changeset(struct, params \\ %{} )  do
    struct
    |> cast(params, [:email, :provider, :token, :nickname, :avatar_url])
    |> validate_required([:email, :provider, :token])
  end
end

web/controllers/auth_controller.ex
defmodule CarlabsComments.AuthController do
  use CarlabsComments.Web, :controller
  plug Ueberauth

  alias CarlabsComments.User

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, params) do
    user_params = %{token: auth.credentials.token, email: auth.info.email, nickname: auth.info.nickname, avatar_url: auth.info.urls.avatar_url, provider: "github"}

    changeset = User.changeset(%User{}, user_params)

    signin(conn, changeset)
  end

  defp signin(conn, changeset) do
    case insert_or_update_user(changeset) do
      {:ok, user} ->
        conn
        |> put_session(:user_id, user.id)
        |> redirect(to: static_path(conn, "/"))
      {:error, _reason} ->
        conn 
          |> redirect(to: static_path(conn, "/"))
    end
  end

  def signout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: static_path(conn, "/"))
  end

  defp insert_or_update_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      nil ->
        Repo.insert(changeset)
      user ->
        {:ok, user}
    end
  end
end

web/controllers/comment_controller.ex
defmodule CarlabsComments.CommentController do
  use CarlabsComments.Web, :controller

  alias CarlabsComments.Comment

  def index(conn, _params) do
   comments = 
    Repo.all(Comment)
      |> Repo.preload(:user)

   render conn, comments: comments
  end

  def create(conn, params) do
    changeset = conn.assigns.user
    |> build_assoc(:comments)
    |> Comment.changeset(params)
   # changeset = Comment.changeset(%Comment{}, params)

    case Repo.insert(changeset) do
      {:ok, comment} ->
        conn
        |> put_status(:created)
        |> put_resp_header("location", comment_path(conn, :show, comment))
        |> render("show.json", comment: comment)
      {:error, changeset} -> 
        conn
        |> put_status(:unprocessable_entity)
        |> render("error.json", changeset: changeset)
    end
  end
end

web/controllers/page_controller.ex
defmodule CarlabsComments.PageController do
  use CarlabsComments.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/comment_view.ex
defmodule CarlabsComments.CommentView do
  use CarlabsComments.Web, :view

  def render("index.json", %{comments: comments}) do
    comments
  end
  def render("create.json", %{comment: comment}), do: comment
  def render("error.json", %{changeset: changeset}), do: changeset



end

web/views/error_view.ex
defmodule CarlabsComments.ErrorView do
  use CarlabsComments.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule CarlabsComments.LayoutView do
  use CarlabsComments.Web, :view
end

web/views/page_view.ex
defmodule CarlabsComments.PageView do
  use CarlabsComments.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Carlabs Comments!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = "<%= Phoenix.Token.sign(CarlabsComments.Endpoint, "key", @conn.assigns.user.id) %>"
      <% end %>
    </script>
  </head>

  <body>
  <nav class="blue lighten-1">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo"> Carlabs Comments </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign Out", to: auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Github", to: auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
      </ul>
      </div>
    </nav>
    <div class="container">
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div id="elm-target"></div>